baseURL = ""
languageCode = "en-us"
title = "Black Ohio Newspapers"
theme = "chnm"

[permalinks]
    blog = "/:title/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "topics"
    name = "Topics"
    url = "/topics"
    weight = 20

  [[menu.main]]
    identifier = "advertisements"
    name = "Advertisements"
    url = "/advertisements"
    weight = 30

  [[menu.main]]
    identifier = "data"
    name = "Data"
    url = "/data"
    weight = 40

 [[menu.main]]
    identifier = "maps"
    name = "Maps"
    url = "/maps"
    weight = 50

 [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 60