# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "RRCHNM"
license = "MIT"
licenselink = "https://github.com/chnm/black-ohio-newspapers/tree/main/www"
description = "A basic theme for projects at the Roy Rosenzweig Center for History and New Media at George Mason University."
homepage = "http://example.com/"
tags = ["minimal", "simple-css"]
features = []
min_version = "0.41.0"

[author]
  name = "Jason Heppler"
  homepage = "https://jasonheppler.org"

