baseURL: "http://chnm-dev.jasonheppler.org"
languageCode: en-us
title: The Ohio Black Press in the 19th Century
theme: chnm

params:
  author: "Jewon Woo"
  author_homepage: "https://chnm.gmu.edu"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "What the Subscribers Read"
      url: "/topics"
      weight: 20
    - name: "What the Advertisers Sold"
      url: "/advertisements"
      weight: 30
    - name: "What the Editors Reprinted"
      url: "/maps"
      weight: 40
    - name: "Data"
      url: "/data"
      weight: 50
    - name: "About"
      url: "/about"
      weight: 60
